sudo: required
services:
  - docker

script:
  - curl https://raw.githubusercontent.com/nouchka/japromis.katagena.com/master/resume.json > resume.json
  - docker-compose -f docker-compose.test.yml up
  - if [[ ! -f "index.html" ]]; then exit 1; fi

notifications:
  email: docker@katagena.com
