hackmyresume:
  image: nginx
  ports:
    - "127.0.0.1:8001:80"
  volumes_from:
    - generate
generate:
  image: nouchka/hackmyresume
  environment:
    - OUTPUT_FORMAT=kendall
  volumes_from:
    - fetch
fetch:
  image: nouchka/hackmyresume
  command: curl -o /usr/share/nginx/html/resume.json https://raw.githubusercontent.com/hacksalot/HackMyResume/master/test/resumes/jrs-0.0.0/jane-q-fullstacker.json
