hackmyresume:
  image: nginx
  restart: always
  ports:
    - "127.0.0.1:8001:80"
  volumes_from:
    - generate
generate:
  image: nouchka/hackmyresume
  environment:
    - OUTPUT_TEMPLATE=kendall
    - PHONE=+33602030405
    - EMAIL=docker@katagena.com
    - ADDRESS=25 Rue Delphin Loche
  volumes_from:
    - fetch
fetch:
  image: nouchka/hackmyresume
  command: curl -o /usr/share/nginx/html/resume.json https://raw.githubusercontent.com/nouchka/docker-hackmyresume/master/resume.json
